### ISSUE TITLE
文本分类中，原文中的spo为什么要用字母代替

### ISSUE THREAD

**Issue by zhouhui1992** [percent4/spo_extract_platform#3]

**Comment by percent4** [comment]
没有用字母代替，是用*代替。

**Comment by zhouhui1992** [comment]
> 没有用字母代替，是用*代替。

`# 示例语句及预处理
text1 = '伊朗卫生部#副部长#哈里奇#外媒称，伊朗卫生部副部长哈里奇确诊感染新型冠状病毒。'
s, p, o, doc = text1.split('#')
text = '#'.join([s, p, o, doc.replace(s, len(s)*'S').replace(p, len(p)*'P').replace(o, len(o)*'O')])
print(text)` 
这一步替换doc的好处是什么呢？

**Comment by percent4** [comment]
这是为了确定抽取的三元组是否是有效的三元组。
