### ISSUE TITLE
404Notfound

### ISSUE THREAD

**Issue by iamdawn** [percent4/spo_extract_platform#9]
运行跑不出页面，求大佬指点一下。
![image](https://user-images.githubusercontent.com/46715453/99499309-a6d82500-29b3-11eb-947c-57dd08505f13.png)

**Comment by Emir-Liu** [comment]
你的位置不对，看实例图片应该是
http://localhost:12308/spo_extract
但是我会报告400: Bad Request
解决了吗楼主

**Comment by Emir-Liu** [comment]
```bash
http://localhost:12308/spo_extract?text=3月5日下午，上海市政协副主席黄震考察了明略科技集团上海办公室，了解该集团防疫和复工复产情况。
```
你试试上面的,我看了一下代码应该这样就好了。
